name: reev_points_mobile
description: REEV Coffee

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # QR Code
  mobile_scanner: ^3.5.6
  
  # Camera & Permissions
  permission_handler: ^11.3.1
  
  # HTTP & API
  http: ^1.1.0
  
  # Storage
  shared_preferences: ^2.2.3
  
  # State Management
  provider: ^6.1.1
  
  # QR Code Generation
  qr_flutter: ^4.1.0
  
  # TODO: Re-add Firebase after fixing web compatibility
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  # flutter_local_notifications: ^16.3.0
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.5
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
