name: iOS Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install Flutter Dependencies
      run: |
        flutter clean
        rm -f pubspec.lock
        flutter pub cache clean
        flutter pub get
        cd ios && rm -rf Pods Podfile.lock && pod install --repo-update
      
    - name: Verify iOS Configuration
      run: |
        # Verify DEVELOPMENT_TEAM is set
        grep -n "DEVELOPMENT_TEAM" ios/Runner.xcodeproj/project.pbxproj || echo "DEVELOPMENT_TEAM not found"
        
    - name: Build iOS (No Codesign)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Upload iOS Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-output
        path: |
          build/ios/iphoneos/Runner.app
          build/ios/archive/Runner.xcarchive
        retention-days: 30
        
    - name: Build Success Notification
      run: |
        echo "✅ iOS build completed successfully!"
        echo "📱 App built for: com.reev.reevPointsMobile"
        echo "🎯 Build configuration: Release (no codesign)"
        ls -la build/ios/iphoneos/ || echo "Build output directory not found"
