name: iOS Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install Flutter Dependencies
      run: |
        flutter clean
        flutter pub get
        cd ios && pod install --repo-update
      
    - name: Verify iOS Configuration
      run: |
        # Verify DEVELOPMENT_TEAM is set
        grep -n "DEVELOPMENT_TEAM" ios/Runner.xcodeproj/project.pbxproj || echo "DEVELOPMENT_TEAM not found"
        
    - name: Build iOS (No Codesign)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Create Keychain and Import Certificate
      run: |
        # Create keychain
        security create-keychain -p "temp123" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temp123" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        
        # Import certificate
        echo "${{ secrets.CERTIFICATES_P12 }}" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "${{ secrets.CERTIFICATES_PASSWORD }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "temp123" build.keychain
        
    - name: Create Provisioning Profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "Provisioning profile creation skipped for now"
        
    - name: Build and Archive iOS App
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath Runner.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/Runner.xcarchive
